### Renommer le fichier en application.secrets.yml et mettez bon identificant de connexion au serveur git
server.git:
  uri: https://github.com/usernamexxxxx
  username: usernamexxxxx
  password: password_or_token_xxxxx

