server:
  port: 0
spring:
  application:
    name: users-ws
    instance_id: ${random.value}
  devtools:
    restart:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - health
          - mappings
          - httpexchanges
          - info
  endpoint:
    health:
      show-details: always
    busrefresh:
      enabled: true

application:
  token:
    expiration-time: 3600 # En seconde
    secret: dd9v6Vp5DqObDoaKCuG6+gMgmkkdFjmjjP2P5K6ZMyDCrP2OU/7HQ+xND+TjmmR2QTYx7Kq91UqQbXTCFoz2ug==
  login-url-path: /users/login