version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: photoAppDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pwd
      # Optionnel : pour créer plusieurs bases
#      POSTGRES_MULTIPLE_DATABASES: photoAppDB,zipkinDB
    ports:
      - "25432:5432"
#    volumes:
      # Persistance des données
#      - postgres_data:/var/lib/postgresql/data
      # 🔥 Scripts d'initialisation pour Zipkin
#      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
    # Optionnel : healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d photoAppDB"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Interface d'administration (optionnel)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "28080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge