server:
  port: 0
spring:
  application:
    name: account-ws
  devtools:
    restart:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka


management:
  endpoint.gateway.enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - busrefresh
          - health
          - mappings
          - info
